//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTaskMaterials
    {
        public int TaskMaterialID { get; set; }
        public int TaskID { get; set; }
        public int MaterialID { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual ProductionTasks ProductionTasks { get; set; }
        public virtual RawMaterials RawMaterials { get; set; }
    }
}
