//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionTasks()
        {
            this.FinishedBatches = new HashSet<FinishedBatches>();
            this.ProductionTaskMaterials = new HashSet<ProductionTaskMaterials>();
        }
    
        public int TaskID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime PlannedEndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public string Status { get; set; }
        public int AssignedToUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinishedBatches> FinishedBatches { get; set; }
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionTaskMaterials> ProductionTaskMaterials { get; set; }
        public virtual Users Users { get; set; }
    }
}
