//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public bool IsAvailable { get; set; }
        public int BeverageTypeID { get; set; }
        public int CategoryID { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual BeverageTypes BeverageTypes { get; set; }
        public virtual ProductCategories ProductCategories { get; set; }
    }
}
