//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        public int ShipmentID { get; set; }
        public int OrderID { get; set; }
        public int BatchID { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public string DocumentNumber { get; set; }
        public int ShippedByUserID { get; set; }
    
        public virtual FinishedBatches FinishedBatches { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
    }
}
