//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxReports
    {
        public int ReportID { get; set; }
        public System.DateTime ReportMonth { get; set; }
        public decimal TotalRevenue { get; set; }
        public decimal TotalCost { get; set; }
        public decimal VAT { get; set; }
        public int PreparedByUserID { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
